logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
security:
    jwt:
        expiration-time: 86400000
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
    forward-headers-strategy: framework
spring:
    datasource:
        password: root
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/bill
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        open-in-view: false

    security:
        oauth2:
            client:
                access-token-uri: http://localhost:8080/auth/login
    # Redis Config
    cache:
        type: redis
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        time-to-live: 60000